// Buscar produtos
GET http://localhost:3000/produtos

###

// Criar produto
POST http://localhost:3000/produto/
Content-Type: application/json

{
    "preco": 355
}

###
// Buscar por id
GET http://localhost:3000/produto/14
# 

###
// Atualizar parcialmente
PATCH http://localhost:3000/produto/18
Content-Type: application/json

{
    "name": "Produto atualizado de novo"
}

###
DELETE  http://localhost:3000/produto/1

###
DELETE  http://localhost:3000/produtos
